TASK : how to create matrices and perform common matrix operations using built-in numpy methods.

In [ ]:
# import required library

In [11]:
import numpy as np
import time

Built-in NumPy methods are 100-1000 times faster than Python loop Implementation

In [ ]:
#test and compare performance of numpy vs plain python loop - dot product
n = 10000000

In [14]:
#vector
n = 10000000
a = [1] * n
b = [2] * n

start = time.time()
c = [0] * n

for i in range(n):
    c[i] = a[i] + b[i]

end = time.time()

print("Time taken from Vector:",end-start)

Time taken from Vector: 1.704817771911621


In [16]:
#Numpy
start = time.time()

a_np = np.arange(n) * 1
b_np = np.arange(n) * 2

c_np = a_np + b_np

end = time.time()

print("Time taken from Numpy:",end-start)

Time taken from Numpy: 0.21118783950805664


Demo NumPy built-ins vs Python loop

In [ ]:
# create 2 matrices using numpy array

In [22]:
A = np.array([[1,2,3],[0,1,0],[0,0,1]]) #matrix = A
B = np.array([[0,1,0],[1,0,0],[1,2,1]])  #matrix = B

In [25]:
print("Shape of A:",A.shape)
print("Shape of B:",B.shape)

Shape of A: (3, 3)
Shape of B: (3, 3)


In [26]:
A

array([[1, 2, 3],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
B

array([[0, 1, 0],
       [1, 0, 0],
       [1, 2, 1]])

In [2]:
# find sum of the matrices

In [28]:
print(A + B)

[[1 3 3]
 [1 1 0]
 [1 2 2]]


In [3]:
# find difference of the matrices

In [33]:
print(A - B)

[[ 1  1  3]
 [-1  1  0]
 [-1 -2  0]]


In [4]:
# finding product of 2 matrices

In [34]:
print(A @ B)
print(np.matmul(A,B))

[[5 7 3]
 [1 0 0]
 [1 2 1]]
[[5 7 3]
 [1 0 0]
 [1 2 1]]


In [5]:
# finding transpose of a matrix

In [36]:
print(A.T)
print(np.transpose(A))

[[1 0 0]
 [2 1 0]
 [3 0 1]]
[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [6]:
# finding determinant of a matrix

In [38]:
print(np.linalg.det(A))
print(np.linalg.det(B))

1.0
-1.0


In [7]:
# finding inverse of a matrix

In [39]:
print(np.linalg.inv(A))
print(np.linalg.inv(B))

[[ 1. -2. -3.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-2. -1.  1.]]


In [8]:
# finding trace of a matrix

In [40]:
print(np.linalg.trace(A))
print(np.linalg.trace(B))

3
1


In [9]:
# finding rank of a matrix

In [41]:
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

3
3


In [10]:
# finding eigen value & Eigen vector of a matrix

In [42]:
print(np.linalg.eig(A))
print(np.linalg.eig(B))

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.40148683e-17]]))
EigResult(eigenvalues=array([ 1.,  1., -1.]), eigenvectors=array([[ 0.00000000e+00,  7.40148683e-17,  6.66666667e-01],
       [ 0.00000000e+00,  7.40148683e-17, -6.66666667e-01],
       [ 1.00000000e+00, -1.00000000e+00,  3.33333333e-01]]))
