In [2]:
import numpy as np

In [3]:
#create an array

arr = np.array([1,2,3,4,5,6])

#Printing arrays...
print("Arrays:",arr)

Arrays: [1 2 3 4 5 6]


In [4]:
#Create a 2D Array

arr2D = np.array([[1,2,3],
                  [4,5,6]])

#printing 2D array...
print("2D Arrays:",arr2D)

2D Arrays: [[1 2 3]
 [4 5 6]]


In [5]:
#Array of Zeros
zeros = np.zeros(5)

#print array..
print("Zero array:",zeros)

Zero array: [0. 0. 0. 0. 0.]


In [6]:
#Create a 3×3 array filled with ones.
ones = np.ones((3,3))

#printing arrays
print("Ones Arrays:",ones)

Ones Arrays: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Create an array with numbers from 0 to 9

arr = np.arange(0,10)

#print arrays...
print("arrays:",arr)

arrays: [0 1 2 3 4 5 6 7 8 9]


In [8]:
#Find the shape of the array np.array([[1,2,3],[4,5,6]])
arr = np.array([[1,2,3],[4,5,6]])

#printing arrays shape...
print("Shapes:",arr.shape)

#Check the data type of an array
print("Data type:",arr.dtype)

Shapes: (2, 3)
Data type: int64


In [9]:
#Reshape an array of numbers from 1 to 6 into a 2×3 array

arr = np.arange(1,7)

#Reshapeing array..
reshape = arr.reshape(2,3)

#printing arrays..
print("Reshape Arrays:",reshape)

Reshape Arrays: [[1 2 3]
 [4 5 6]]


In [10]:
#Access the element 5 from the array [[1,2,3],[4,5,6]].
arr = np.array([[1,2,3],[4,5,6]])

#Access the element 5
print("Access the element 5:",arr[1,1])

Access the element 5: 5


In [11]:
#Access the element 5 from the array [[1,2,3],[4,5,6]]
arr = np.array([[1,2,3],[4,5,6]])

#printing the element 5
print("Element 5:",int(arr[1, 1]))

Element 5: 5


In [12]:
#Get the first three elements from array [10, 20, 30, 40, 50].
arr =  np.array([10, 20, 30, 40, 50])

idx = [0,1,2]

print(arr[idx])

[10 20 30]


In [13]:
#Add two arrays [1,2,3] and [4,5,6]

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = arr1 + arr2

print(arr)

[5 7 9]


In [14]:
#Multiply all elements of an array by 2.
arr = np.array([1,2,3])

arr1 = arr*2

print(arr1)

[2 4 6]


In [15]:
#Find the mean of array [1,2,3,4,5]
array_1 = np.array([1,2,3,4,5])

array_mean = np.mean(array_1)
print(int(array_mean))

3


In [16]:
#Find the maximum and minimum values of an array.
print(int(np.min(array_1)))
print(int(np.max(array_1)))

1
5


In [17]:
#Find the sum of all elements in an array.
print(np.sum(array_1))

15


In [18]:
#Get elements greater than 3 from [1,2,3,4,5]
array = np.array([1,2,3,4,5])
msk = array > 3

#printing the array..
print("Arrays:",array[msk])

Arrays: [4 5]


In [19]:
#Create a 3×3 identity matrix.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Generate 5 random numbers between 0 and 1
random_num = np.random.rand(5)

#printing the num..
print("Random Nums:",random_num)

Random Nums: [0.63849852 0.85010048 0.1699517  0.47995028 0.80929682]


In [21]:
#Convert a 2D array into a 1D array
arr2D = np.array([[1,2,3],
                  [4,5,6]])

#Convert the array in 1D array..
arr1D = arr2D.flatten()

#printing the array..
print("Printing the Flatten array:",arr1D)

Printing the Flatten array: [1 2 3 4 5 6]


avr: 3.0
min_val: 1
max_val: 5
