In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

#average array
avr = np.mean(arr)
print("avr:",avr)

#min of array
min_val = np.min(arr)
print("min_val:",min_val)

#max of array
max_val = np.max(arr)
print("max_val:",max_val)

avr: 3.0
min_val: 1
max_val: 5


In [3]:
#create a 3x3 numpy array with value from 10 to 18.
array = np.arange(10,19)

#reshape the array...
reshape_arr = array.reshape((3,3))

#printing the array...
print("ARRAYS:",reshape_arr)

ARRAYS: [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [4]:
#FIND MEAN, MEDIAN AND STD OF AN ARRAY...
arr = np.arange(1,13)

#mean of array..
mean_arr = np.mean(arr)
print("Mean:",mean_arr)

#median of array
median_arr = np.median(arr)
print("Median:",median_arr)

#std of array
std_arr = np.std(arr)
print("STD:",round(std_arr,2))

Mean: 6.5
Median: 6.5
STD: 3.45


In [5]:
#replace all even number with zero
arr = np.arange(1,13)

repalced_arr = arr[arr % 2 == 0] = 0
print(arr)

[ 1  0  3  0  5  0  7  0  9  0 11  0]


In [6]:
#abstract elements greter than 15.
arr = np.array([1,23,4,56,78,8])

msk = arr > 15
print("Element Gretter Than 15:",arr[msk])

Element Gretter Than 15: [23 56 78]


In [7]:
#create identy matrix 4x4.

IDENTY_MATRIX = np.eye(4)
print(IDENTY_MATRIX)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr = np.arange(1,11)

reshape_arr = arr.reshape((2,5))
reshape_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
#How do you create 2D numpy array and compute row wise and column wise sum.
array = np.array([[1,2,3],
                 [4,5,6]])

sum_row = np.sum(array, axis=1)
sum_colm = np.sum(array, axis=0)

print("Sum of Row:",sum_row)
print("Sum of col:",sum_colm)

Sum of Row: [ 6 15]
Sum of col: [5 7 9]


In [18]:
#How do you reshape a numpy array without changeing its data.
arr = np.arange(1,11)

#Reshape the data...
reshape_arr = arr.reshape((2,5))

#Printing the array..
print(reshape_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
#Any Example of Broadcasting example:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

#Broadcasting Array...
broadcast_arr = arr1 + arr2

#Printing the Arrays...
print("Sum of Array:",broadcast_arr)

Sum of Array: [ 7  9 11 13 15]


In [24]:
#Any Example of Broadcasting example:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

#Broadcasting Array...
broadcast_arr = arr1 * arr2

#Printing the Arrays...
print("Product of Array:",broadcast_arr)

Product of Array: [ 6 14 24 36 50]
