In [1]:
#USING PYHTON LIST....
import numpy as np
import time

size = 1_000_000_0
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [ x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])
print("Time_Taken:",end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Time_Taken: 3.6550400257110596


In [2]:
#USING NUMPY ARRAY....
import numpy as np
import time

size = 1_000_000_0
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])
print("Time_Taken:",end - start)

[ 0  2  4  6  8 10 12 14 16 18]
Time_Taken: 0.4194173812866211


In [3]:
#PYTHON ZIP EXPLAINED....
l1 =[1,2,3,4]
l2 =[5,6,7,8]
list(zip(l1,l2))

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([ [1,2,3], [4,5,6]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(2, 3)

In [9]:
#NumPy arrays use significantly less memory compared to Python lists.
import sys

list_size = list(range(1000))
numpy_size = np.array(list_size)

print("Python_Size:", sys.getsizeof(list_size) * len(list_size), "Bytes")
print("Numpy_Size:", numpy_size.nbytes, "Bytes")

Python_Size: 8056000 Bytes
Numpy_Size: 8000 Bytes


In [10]:
import time

#Pyhton list loop....
list1 = [1,2,3]
start = time.time()
list_square = [x**2 for x in list1]
end = time.time()
print(list_square)
print("Time_Taken:",end - start)

# numpy (Vectorization)
arr1 = np.array([1,2,3])
start = time.time()
numpy_sqaure = arr1 ** 2
end = time.time()
print(numpy_sqaure)
print("Time_Taken:",end - start)

[1, 4, 9]
Time_Taken: 0.00019359588623046875
[1 4 9]
Time_Taken: 0.0011334419250488281


In [18]:
import numpy as np

# Createing 1D array...
arr1 = np.array([1,2,3,4,5,6])
print("Array_1:",arr1)

# Createing 2D array....
arr2 = np.array([[1,2,3], 
                 [4,5,6]])
print("Array_2:",arr2)

#Print Type and Shape....
print("Type:",type(arr1))
print("Shape:",arr2.shape)

Array_1: [1 2 3 4 5 6]
Array_2: [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
