In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print("Array_1:",arr1)
print("Array_2:",arr2)

Array_1: [1 2 3 4]
Array_2: [[1 2 3 4]
 [5 6 7 8]]


In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [21]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
print("Shape:",my_arr.shape)
print("Size:",my_arr.size)
print("Dimension:",my_arr.ndim)
print("Data Type:",my_arr.dtype)

Shape: (4, 3)
Size: 12
Dimension: 2
Data Type: int64


In [24]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype = "float32")
print("New_Dtype:",my_arr.dtype)

New_Dtype: float32


In [25]:
n = my_arr.astype('float32')
n.dtype

dtype('float32')

In [32]:
arr1 = np.array([1.1,2.3])
arr1.dtype
arr_int = arr1.astype(np.int32)
arr_int.dtype

dtype('int32')

In [39]:
#Reshapeing and flattening arrays...
arrays = np.array([[1,2,3],[4,5,6]])
print("Shape:",arrays.shape)

#Reshape to 3,2....
reshape_arr = arrays.reshape((3,2))
print("Reshape:",reshape_arr.shape)

#Flattening Array....
flatten = arrays.flatten() #Converted the 2D array to 1D..
print("Flattend_Array:",flatten)

Shape: (2, 3)
Reshape: (3, 2)
Flattend_Array: [1 2 3 4 5 6]
