In [2]:
#Create a 3×3 array filled with random numbers and print its shape.
import numpy as np #import numpy as np....

#It take random integer array...
rand_int_arr = np.random.randint(1,10,size = (3,3))

#Print its array  and shape...
print("Random_int_Array:",rand_int_arr)
print("Shape:",rand_int_arr.shape)

Random_int_Array: [[3 2 9]
 [6 1 4]
 [8 4 9]]
Shape: (3, 3)


In [3]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
array = np.array([1.1, 2.2, 3.3])

#Type Of Array....
print("Before_Change:",array.dtype)

#Convert the Float to Int...
arr_int = array.astype(np.int32)
print("After_Change:",arr_int.dtype)

Before_Change: float64
After_Change: int32


In [4]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
arr = np.array([1, 2, 3, 4, 5, 6])

#Use fancy indexing to extract even numbers
msk = arr % 2 == 0

#print the output
print("Even_Num:",arr[msk])

Even_Num: [2 4 6]


In [5]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr = np.array([1,2,3,4,5,6,7,8,9])

#Reshape.....
Reshape_Arr = arr.reshape(3,3)

#Print Reshape Value...
print("Reshape_Value:",Reshape_Arr)

Reshape_Value: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr = np.array([23,4,56,90,60,78,99])

#masking to filter numbers greater than 50
msk = arr > 50

#Print boolean masking to filter numbers greater than 50 in an array.
print("Gretter_than_50:",arr[msk])

Gretter_than_50: [56 90 60 78 99]
