In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[0:4]

array([1, 2, 3, 4])

In [7]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [14]:
b = flat[3:7].copy()

In [15]:
b

array([99,  5,  6,  7])

In [16]:
b[0] = 99

In [17]:
b

array([99,  5,  6,  7])

In [18]:
flat

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 11, 12, 13])

In [22]:
arr = np.array([10,20,30,40])
print(arr[0]) #10
print(arr[-1]) #40

10
40


In [26]:
arr = np.array([10,20,30,40,50])
print(arr[:3])
print(arr[0:2])
print(arr[::2])

[10 20 30]
[10 20]
[10 30 50]


In [30]:
sliced = arr[1:4] #It take the array from = 20 - 40
sliced[0] = 33
print(arr)

[10 33 30 40 50]


#Fancy Indexing & Boolean Masking

In [34]:
arr = np.array([10,25,48,96,74,10])
idx = [0,4,5]
print(arr[idx])

[10 74 10]


In [36]:
arr = np.array([10,25,48,96,74,10])
msk = arr > 50
print(arr[msk])

[96 74]
