1.Understanding Axes in NumPy

In [1]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

#Printing the array....
print("Array:",arr)

#Suming the arrays rows and columns....
print("\nSuming the columns:",np.sum(arr, axis=0)) #Suming the columns....
print("Suming the rows:",np.sum(arr, axis=1)) #Suming the rows...

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Suming the columns: [12 15 18]
Suming the rows: [ 6 15 24]


2.Indexing in Multidimensional Arrays

In [2]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Accessing an element
print("Accesing row= 0 and column= 2:",arr[0,2])
print("Accesing row= 1 and column= 2:",arr[1,2])
print("Accesing row= 2 and column= 2:",arr[2,2])

# Extracts first 2 rows and last 2 columns
print("\nExtracts first 2 rows and last 2 columns:",arr[0:2, 1:3])
print("\nExtracts first 3 rows and last 1 columns:",arr[0:3, 0])

Accesing row= 0 and column= 2: 3
Accesing row= 1 and column= 2: 6
Accesing row= 2 and column= 2: 9

Extracts first 2 rows and last 2 columns: [[2 3]
 [5 6]]

Extracts first 3 rows and last 1 columns: [1 4 7]


3.Indexing in 3D Arrays

In [3]:
arr3D = np.array([[
    [1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]
]])

#Printing the 3D Arrays..
print("The 3D arrays:",arr3D)

#Printing the Shape
print("\nShape:",arr3D.shape)

#Accessing elements in 3D:
#Second sheet, first row, third column
print("\nAcessing Second sheet first row and third column:",arr3D[1, 0, 2])
print("Acessing the both sheet Both first row and All column:",arr3D[:, 0, :])

The 3D arrays: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)

Acessing Second sheet first row and third column: 9
Acessing the both sheet Both first row and All column: [[1 2 3]
 [7 8 9]]


4.Practical Example: Selecting Data Along Axes

In [4]:
# Get all rows of the first column
first_colm = arr[:,0]
print("Frist colomn of all rows in arrays:",first_colm)

# Get the first row from each "sheet" in a 3D array
first_row = arr3D[:,0,:]
print(" first row from each sheet in a 3D array:",first_row)

Frist colomn of all rows in arrays: [1 4 7]
 first row from each sheet in a 3D array: [[1 2 3]
 [7 8 9]]


4.Changing Data Along an Axis

In [5]:
print("Array:",arr)

# Replace all elements in column 1 with 0
arr[:,1] = 0
print("\nArray:",arr)

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array: [[1 0 3]
 [4 0 6]
 [7 0 9]]
