In [1]:
import numpy as np
import time

# Looping Over Arrays in Python
arr = np.array([1,2,3,4,5,6])
result = []

#using loop square the array..
start = time.time()
for num in arr:
    result.append(int(num ** 2))
end = time.time()

#Printing the result....
print("Result:",result)
print("Time taken:",end-start)

Result: [1, 4, 9, 16, 25, 36]
Time taken: 0.000415802001953125


In [2]:
#Vectorized Operation
arr = np.array([1,2,3,4,5,6])

start = time.time()
result = arr**2
end = time.time()

print("Result:",result)
print("Time taken:",end-start)

Result: [ 1  4  9 16 25 36]
Time taken: 0.0005972385406494141


In [3]:
#Broadcasting with Scalar
arr = np.array([1,2,3,4,5,6])
result = arr + 10
print("Array:",arr)

print("Output:",result)

Array: [1 2 3 4 5 6]
Output: [11 12 13 14 15 16]


In [4]:
# Broadcasting with Two Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print("Result:",result)

Result: [5 7 9]


In [5]:
#Broadcasting a 2D Array and a 1D Array

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([1,2,3])

result = arr1 + arr2
print("Result:",result)

Result: [[2 4 6]
 [5 7 9]]


In [6]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis = 0)
std = data.std(axis = 0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print("Normalized data:",normalized_data)

Normalized data: [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
